### ISSUE TITLE
When loaning books out, the loaned books will jump to the top of book list upon closing and reentering the app

### ISSUE THREAD

**Issue by sprintaway** [AY2223S1-CS2103-F14-4/tp#126]

**Comment by parth-io** [comment]
This issues happens because when we relaunch the app, loaned books get parsed first due to the way I implemented the `Person` deserialising mechanism. If a `Person` has any loans, the loaned `Books` also get deserialised and added to the `BookList`.

Two approaches to get a more consistent behaviour
1. Either we update the UI to bubble up a newly loaned book
2. Or we have a serial number for each book, then we organise the book lists by the serial number

What do you think?

**Comment by sprintaway** [comment]
I think that the first one is easier to implement but the second one makes more sense. Another possible way is to sort the book by Book Title for example whenever a book is added or loaned so that it always maintains the order in alphabetical order but it might be a hassle to maintain. 

But if we do implement the first one it is also feasible since we can claim that it is a feature and not a bug because it is logical for loaned books to show up at the top for the librarian to see as loaned books have a due date making them more important to track.

**Comment by parth-io** [comment]
As discussed in the team meeting, we can change the UI to show the loaned book at the top. This involves refreshing the UI after a `loan` or `return` command as well
